import { z } from "zod";

export const createListingValidateor = z.object({
  // userId: z.string().
  condition: z.string().nonempty("Please select listing condition"),
  make: z.string().nonempty("Please select make"),
  model: z.string().nonempty("Please select model"),
  year: z.string().optional(),
  carType: z.string().nonempty("Please select mileage"),
  mileage: z.string().nonempty("Please select mileage"),
  fuelType: z.string().nonempty("Please select fuel type"),
  engineType: z.string().nonempty("Please select engine type"),
  transmission: z.string().nonempty("Please select transmssion type"),
  price: z.string().nonempty("Please enter listing price"),
  drive: z.string().optional(),
  ext_color: z.string().nonempty("Please enter listing Exterior color"),
  int_color: z.string().optional(),
  vin: z.string().optional(),
  location: z.string().nonempty("Please enter location"),
  lng: z.string().optional(),
  lat: z.string().optional(),
  air_condition: z.string().optional(),
  backup_camera: z.string().optional(),
  cruis_control: z.string().optional(),
  navigation: z.string().optional(),
  bluetooth: z.string().optional(),
  audio: z.string().optional(),
  stereo: z.string().optional(),
  dvd: z.string().optional(),
  airbag_passenger: z.string().optional(),
  airbag_driver: z.string().optional(),
  security_system: z.string().optional(),
  antilock: z.string().optional(),
  heated_seats: z.string().optional(),
  power_seats: z.string().optional(),
  bucket_seat: z.string().optional(),
  leater_seat: z.string().optional(),
  imageUrl: z.string().optional(),
  seller_note: z.string().optional(),
});

// nonempty("Please upload at least 1 photo"),
